### ISSUE TITLE
An error occured for ClassEnhancer "ASM"

### ISSUE THREAD

**Issue by anschall** [google/firing-range#21]
When running 'ant runserver' on Mac OSX 10.13.4 I get the multiple instances of the following error:

`[enhance] Apr. 10, 2018 12:29:57 VORM. org.datanucleus.enhancer.DataNucleusEnhancer addMessage
  [enhance] SCHWERWIEGEND: An error occured for ClassEnhancer "ASM" when trying to call the method "org.datanucleus.enhancer.asm.ASMClassEnhancer" on class "getClassNameForFileName" : null
  [enhance] java.lang.IllegalArgumentException
  [enhance] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
  [enhance] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
  [enhance] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
  [enhance] 	at org.datanucleus.enhancer.asm.ASMClassEnhancer.getClassNameForFileName(ASMClassEnhancer.java:155)
  [enhance] 	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
  [enhance] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [enhance] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  [enhance] 	at org.datanucleus.enhancer.DataNucleusEnhancer.getClassNameForFilename(DataNucleusEnhancer.java:920)
  [enhance] 	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:736)
  [enhance] 	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:545)
  [enhance] 	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1252)
  [enhance] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [enhance] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  [enhance] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [enhance] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  [enhance] 	at com.google.appengine.tools.enhancer.Enhancer.execute(Enhancer.java:74)
  [enhance] 	at com.google.appengine.tools.enhancer.Enhance.<init>(Enhance.java:70)
  [enhance] 	at com.google.appengine.tools.enhancer.Enhance.main(Enhance.java:50)`

I am using the following Java version:

`$ java --version
java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)`

You can find the full log attached,
[log.log](https://github.com/google/firing-range/files/1891035/log.log)

**Comment by Nexus2k** [comment]
Can you reproduce this with another JDK version?
